force-app/main/default/objects/Exception_Logger__c/Exception_Logger__c.object-meta.xml
<CustomObject>
    <label>Exception Logger</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Logger__c/fields/Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Creation_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Stores the date the Log was created (this is to be able to set Creation Date without having audit field permissions)</description>
    <label>Creation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ucl_ExceptionLoggerTriggerHandler.cls
/**
 * @date 03/27/2020
 * @author Altimetrik
 * 
 * class to handle Exception Logger Trigger
 */
public with sharing class ucl_ExceptionLoggerTriggerHandler {
    public static void handleDeleteException(List<Exception_Logger__c> loggedRecords) {
        for (Exception_Logger__c loggedRecord : loggedRecords) {
            if (!isOneOrMoreMonthsOld(loggedRecord.Creation_Date__c)) {
                loggedRecord.addError('Logs should be kept in the system for at least a month');
            }
        }
    }

    private static Boolean isOneOrMoreMonthsOld(Date creationDate) {
        return creationDate.monthsBetween(Date.today()) >= 1;
    }
}